### ISSUE TITLE
Migrate TODO list to GitHub issues.

### ISSUE THREAD

**Issue by ear1grey** [portsoc/dcalc#1]
## todo

* [x] version control
* [x] desktop view
* [x] github
* [x] calculate rules
  * [x] rule a = (Mean of Year 2 * 0.4) + (Mean of Year 3 * 0.6)  
  * [x] rule b = (Mean of Year 3)
  * [x] rule c = (Median grade of year 2 and year 3)
* validation: https://github.com/portsoc/dcalc/issues/7
* [x] saving
* offline app: https://github.com/portsoc/dcalc/issues/6
* [x] Move TODO list to github issues
  * [x] Started
  * [x] Finished

## maybe
* Simplify: https://github.com/portsoc/dcalc/issues/2
* Share my grades: https://github.com/portsoc/dcalc/issues/3
* Explain Rules: https://github.com/portsoc/dcalc/issues/4
* GPA Predictor: https://github.com/portsoc/dcalc/issues/5

**Comment by ear1grey** [comment]
All entries here have been migrated to separate issues.
